### ISSUE TITLE
okta configuration for corporate account

### ISSUE THREAD

**Issue by resworld** [szamfirov/gocd-okta-oauth-authorization-plugin#1]
Is there any how-to for okta configuration with corporate account? We've tried to configure okta, but we couldn't find auth server option in interface (it is one of the step in installation guide). It will be perfect if can be provided Install instruction for corporate account in okta as well. Thanks for your attention. I’m looking forward to your reply.

**Comment by gkid** [comment]
Also searching for a solution for corporate Okta account.
If anyone has any information that can help - it would be greatly appreciated.

**Comment by Mark-McCracken** [comment]
I've set up with corporate account, typically the API feature isn't enabled by default on corporate accounts, whereas its given free with dev accounts.
I'd advise checking with your Okta account manager, that's what I had to do, to get the feature enabled.
